CREATE TABLE superstore (
    Row_ID INT,
    Order_ID VARCHAR(50),
    Order_Date TEXT,      -- Imported as text first to handle different date formats
    Ship_Date TEXT,
    Ship_Mode VARCHAR(50),
    Customer_ID VARCHAR(50),
    Customer_Name VARCHAR(100),
    Segment VARCHAR(50),
    Country VARCHAR(50),
    City VARCHAR(50),
    State VARCHAR(50),
    Postal_Code VARCHAR(20),
    Region VARCHAR(50),
    Product_ID VARCHAR(50),
    Category VARCHAR(50),
    Sub_Category VARCHAR(50),
    Product_Name TEXT,
    Sales DECIMAL(15,4),
    Quantity INT,
    Discount DECIMAL(15,4),
    Profit DECIMAL(15,4),
    Order_Year INT,
    Order_Month INT,
    Profit_Margin DECIMAL(15,4) -- Added based on your image
);